---
title: "Fragen und Tipps"
toc: true
---

## Tipps & Tricks für den eigenen Medienumgang

-   **Keine Geräte in Schlaf- und Kinderzimmer!**

-   Werden Sie auf die Zeitfresser aufmerksam, **deaktivieren Sie z.B. die Autoplayfunktion** bei YouTube, Netflix etc., setzen Sie sich selber (Zeit-)Limits.

-   **Zeitfressende Apps und Spiele am besten ganz löschen**. Fragen Sie sich auch, ob Sie in jedem "sozialen" Netzwerk aktiv sein müssen.

-   Schauen Sie sich die persönlichen **Nutzungszeiten** einzelner Apps an und versuchen Sie, da wo es sinnvoll ist, zu **reduzieren**. Man kann auch einen Nutzungstimer für einzelne Apps erstellen, dann lässt sich die App nach Ablauf der eingestellten Zeit nicht mehr öffnen (z.B. "Digital Wellbeing" Android, "Bildschirmzeit" iOS).

-   Falls Sie ein Android-Smartphone (kein iPhone) haben, können Sie sich einen **Textlauncher installieren**. Es werden dann alle App-Symbole nur noch als Text angezeigt, was die visuellen Anreize deutlich reduziert. Die einfachste Version ist der [Text Launcher](https://play.google.com/store/apps/details?id=ademar.textlauncher), diesen gibt es auch im freien App-Store [F-Droid](https://f-droid.org/de/packages/ademar.textlauncher/). Der [Olauncher](https://play.google.com/store/apps/details?id=app.olauncher) bietet mehr Anpassungsmöglichkeiten und Hintergrundbilder und der [LessPhone - Minimal Launcher](https://play.google.com/store/apps/details?id=me.aswinmohan.nophone) ist in der Lage, die Smartphonefunktionen bei Bedarf auf ein Minimum zu reduzieren. Alle Apps sind nach eigener Auskunft datensparsam, es werden weder Nutzerdaten erhoben, noch werden diese mit Drittanbietern geteilt.

-   Für **konzentriertes Arbeiten und Lernen**:

    -   Nicht stören-/Fokus-Modus benutzen um Benachrichtigungen stumm und unsichtbar zu schalten,

    -   Wenn möglich offline arbeiten,

    -   Mailprogramm schließen,

    -   Smartphone lautlos stellen und aus dem Sichtfeld legen, am besten in einen anderen Raum (siehe auch folgenden [Blogeintrag](/posts/230923-brain-drain-smartphone/)),

    -   In Pausen so wenig digitale Medien wie möglich nutzen, sonst werden schnell 5 Minuten zu einer halben Stunde ohne nennenswerten Erholungswert.

-   **Handy weglegen**, auch in der Wohnung nicht immer dabeihaben.

-   Probieren Sie auch den **schwarz/weiß-Modus** ihres Smartphones aus, es wird sofort an Attraktivität verlieren.

## 5 Anregungen zur „digitalen Entwöhnung"

1.  **Ab und zu alleine:** Lassen Sie Ihr Smartphone ganz zuhause und gehen Sie, mit „offenen Sinnen", in der Natur spazieren.

2.  **Freiräume:** Versuchen Sie Zuhause einzelne Zonen (z. B. das Schlafzimmer) frei von digitalen Medien zu halten.

3.  **Ruhe bitte:** Stellen Sie so oft wie möglich Ihr Smartphone Lautlos (kein Klingelton und kein Vibrationsalarm). Vor allem wenn Sie konzentriert arbeiten wollen ist dies sinnvoll. Eine Möglichkeit ist es auch, einzelne Apps, die Sie nicht so häufig nutzen, die aber oft mit Benachrichtigungen Ihre Aufmerksamkeit fordern, stummzuschalten.

4.  **Feste Zeiten:** Setzen Sie sich feste Zeiten, auch während der Arbeit, in denen Sie Ihre Mails lesen und beantworten und schließen Sie in Konzentrationsphasen ihr Mailprogramm am besten ganz. Auch im Privaten sollten sie sich Zeiten freihalten, in denen Sie keine Nachrichten lesen und beantworten (z.B. vor dem Frühstück, nach 20 Uhr etc.)

5.  **FREItag:** Trauen Sie sich einen ganzen Tag offline zu sein und keine digitalen Medien zu nutzen. Langeweile sollten Sie unbedingt zulassen. Sie werden überrascht sein.
