---
callout-icon: false
#https://jollydata.blog/posts/2022-08-06-_switching-to-quarto/switching-to-quarto.html
---

::: news
-   

    ##### **7. Dezember**

    "Pisa-Schock" (mal wieder): "[Deutsche Schüler so schlecht wie nie](https://www.tagesschau.de/inland/gesellschaft/pisa-studie-128.html)" (mal wieder):

    > Knapp ein Drittel der 15-Jährigen hat in mindestens einem der drei getesteten Felder nur sehr geringe Kompetenzen. Etwa jeder sechste Jugendliche hat in allen drei Bereichen deutliche Defizite. Die Anteile dieser besonders leistungsschwachen Jugendlichen sind seit 2018 größer geworden und betragen in Mathematik rund 30 Prozent, im Lesen rund 26 Prozent und in den Naturwissenschaften rund 23 Prozent.
    >
    > Der Anteil der besonders leistungsstarken Schülerinnen und Schüler ist wiederum gesunken - in Mathematik auf knapp neun Prozent und im Lesen auf knapp acht Prozent. In den Naturwissenschaften blieb dieser Anteil bei etwa zehn Prozent stabil.

    Was folgt? [Es wird viel geredet werden](https://www.tagesschau.de/inland/innenpolitik/pisa-ergebnisse-reaktionen-100.html) und anschließend vermutlich Symptombekämpfung betrieben. Der zumindest zeitliche Zusammenhang mit der zunehmenden Smartphonenutzung wird dabei weitestgehend ausgeklammert. Dazu fehlen natürlich in den dringend sanierungsbedürftigen Schulen dieses dringend sanierungsbedürftigen Bildungssystem auch noch dringend jede Menge nichtsanierungsbedürftige Lehrer.

    [Dazu ein sehr lesenswertes Interview mit Prof. Gertraud Teuchert-Noodt](https://www.diagnose-funk.org/aktuelles/artikel-archiv/detail&newsid=2037)

-   

    ##### **1. Dezember**

    Wegen der KI: [Uni in Prag schafft Bachelorarbeiten ab](https://www.faz.net/aktuell/karriere-hochschule/hoersaal/erste-uni-schafft-wegen-ki-und-plagiaten-bachelorarbeiten-ab-19353621.html) (Paywall)...

    ...und ersetzt sie möglicherweise durch etwas viel Sinvolleres:

    > Wir werden den Abschluss des Bachelorstudiums auf eine praktische Art und Weise konzipieren, die viel weniger Raum für Plagiate lässt und von der die Studenten viel mehr nützliche Erfahrungen in ihr Leben mitnehmen werden.

-   

    ##### **26. November**

    [Eine knappe Mehrheit der deutschen Bevölkerung befürchtet inzwischen, dass die Digitalisierung zu mehr Ungleichheit im Sozialen und in der Bildung führt.](https://www.ifo.de/publikationen/2023/aufsatz-zeitschrift/chancenungleichheit-bildungssystem) Im Bildungssystem wird dies von 53% der Befragten erwartet (2017 waren es noch 44%), nur noch 13% erwarten keine größere Ungleichheit, 2017 waren es noch 51%.

-   

    ##### **23. November**

    Diese Kundenkarten, die man jetzt überall hat, sind natürlich supersicher, wie alles, wo man heutzutage freiwillig alle seine persönlichen Daten abliefert. [Blöd ist dann nur, wenn man seine Bestellungen (mit Adresse und allem drum&dran natürlich) auf einmal im Internet wiederfindet](https://www.golem.de/news/datenleck-bestelldaten-von-bauhaus-kunden-ueber-suchmaschine-auffindbar-2311-179670.html). Dann können das nämlich alle Anderen auch.

-   

    ##### **15. November**

    KI wird uns alle retten! Jetzt auch davor, dass wir uns für unsere Kinder ständig neue Geschichten ausdenken müssen. [Denn jetzt soll die Toniebox, die uns bisher davor rettet unseren Kindern vorlesen zu müssen, dank KI auch Geschichten "erfinden" können](https://www.heise.de/news/ChatGPT-im-Kinderzimmer-Toniebox-plant-Integration-9497640.html). Das geht ganz einfach in dem man ein Thema, den Namen und das Alter (damit der Inhalt angemessen ist) des Kindes angibt, und fertig ist die Geschichte, in der das eigene Kind endlich der Titelheld sein kann. Es gibt natürlich einen kleinen Haken:

    > ChatGPT kann schon aus knappen Prompts Märchen oder kurze Geschichten generieren -- die Qualität ist allerdings offen bis fragwürdig.\
    > \[...\]\
    > Problematisch ist freilich, dass ChatGPT auch mal halluziniert. Das heißt, die Geschichten können im Zweifel Lücken in der Handlung haben, aber auch problematische Inhalte wiedergeben. Eine Moral von der Geschicht ist nicht unbedingt zu erwarten, kann es aber geben.

    Aber natürlich gibt es Sicherheitsmechanismen die verhindern, dass pornographische oder gewaltvolle Inhalte generiert werden. Ja dann ist das Alles natürlich supersicher und kann zukünftig problemlos in die Kinderzimmer Einzug halten. Nicht.

-   

    ##### **14. November 2023**

    [Nepal vebietet Tik-Tok](https://www.heise.de/news/Nepal-beschliesst-TikTok-Verbot-9466624.html). Alle anderen Sozialen-Netzwerke, die in Nepal tätig sind, müssen Verbindungsbüros in dem Land einrichten.

-   

    ##### **12. November 2023**

    Der Meta-Konzern (Facebook, Instagram etc.) sieht sich aktuell mit dem [Vorwurf der vorsätzlichen Gefährdung Jugendlicher](https://www.heise.de/news/Instagram-Meta-muss-sich-wegen-Gefaehrdung-Jugendlicher-in-den-USA-verantworten-9358881.html) konfrontiert und wird vom US-Bundesstaat Massachusetts angeklagt. Zur Debatte stehen unter anderem die bewusst eingesetzten Mechanismen, Nutzer in der App zu halten und sie zu bewegen, diese auch immer wieder aufzurufen, gepaart mit zu laxen Zugangsbeschränkungen für Instagram (in den USA erst ab 13 Jahren freigegeben) und damit der bewussten Inkaufnahme, Kinder, die noch nicht über die nötigen Kontrollmechanismen sich diesen Produktdesigns willentlich zu entziehen verfügen, zu schädigen.

    > Laut der Klage ist dem Social-Media-Unternehmen aufgrund interner Untersuchungen durchaus bekannt, welche Auswirkungen die Plattformen auf Kinder und Jugendliche haben. Zumal Meta über mehr als 33 Millionen US-Nutzerdaten verfüge und diese analysiere. Auch treffe man gezielt Designentscheidungen, die bekannte Schäden für junge Nutzer verschlimmern würden, wenn dahinter die Aussicht auf mehr Profit stehe. Das Unternehmen stelle sich bewusst gegen die Ergreifung von Maßnahmen, die Schäden von Jugendlichen mildern und das Wohlbefinden verbessern würden.

    An dieser Meldung ist kaum etwas Neues, seit Jahren weiß man, dass sich Zuckerberg um des Profits willens und wider besseren Wissens quasi gegen jeden Nutzerschutz stellt.

    > Zusätzlich habe Meta nicht nur sein Wissen über die von Instagram verursachten Schäden verheimlicht, sondern Kampagnen gestartet, um die Öffentlichkeit zu täuschen und ihr vorzugaukeln, dass Sicherheit und Wohlergehen der Jugendlichen dem Social-Media-Riesen am Herzen liege und Priorität habe. Stattdessen bestreite das Unternehmen einfach die intern bekannten negativen Auswirkungen und entscheide sich gegen abmildernde Maßnahmen, die die eigenen Beschäftigten angeführt hätten.

    Vielleicht erreicht die Klage ja diesmal eine Änderung der Praxis.

-   

    ##### **8. November 2023**

    Kennen Sie das: Sie loggen sich aus dem Netzwerk aus und auf Ihrem Gerät sind alle Daten gelöscht? Klingt komisch, ist aber jetzt zwei [Abi-Klassen aus Koblenz](https://www.swr.de/swraktuell/rheinland-pfalz/koblenz/koblenz-schul-app-panne-abiturienten-verlieren-unterrichtsnotizen-100.html) passiert. Unterrichtsmaterial, Notizen, alles weg, weil ja alles nur noch digital verarbeitet wird. Das ist natürlich Pfusch, denn eine Netzwerkpanne löscht normalerweise keine Daten, aber Pfusch kommt eben schonmal vor. Gut, dass es Backups gibt. Oh, Moment: Offensichtlich hat keiner die Schüler darüber informiert, dass sowas sinnvoll ist und sie sich selber darum kümmern müssen:

    > Die Stadt Koblenz bedauert die Schwierigkeiten, die vor allem die Abiturienten jetzt haben. Sie betont aber auch, dass es wichtig sei, dass die Schülerinnen und Schüler immer wieder Kopien ihrer Dokumente für den Notfall abspeicherten. Allerdings räumt die Stadt auch ein: "Dies ist, wie wir jetzt wissen, jedoch nicht flächendeckend kommuniziert worden."
    >
    > Beim Speichern müssten sich die Schülerinnen und Schüler allerdings an bestimmte Sicherheitsstandards halten: Sie dürften ihre Daten nicht in Clouds speichern, deren Server außerhalb der EU betrieben werden. Das sei wichtig, um sensible und persönliche Daten zu schützen.

    Offensichtlich gibt es ja heute neben der Cloud (und KI natürlich!) überhaupt keine anderen Datenverarbeitungsmöglichkeiten mehr... kann man also nix machen (wie hat man das eigentlich gemacht, bevor es die Cloud gab?). Man kann Backups übrigens auch verschlüsseln und dann in der Cloud speichern, wobei das fast etwas lächerlich ist, da die [Geräte und Apps](https://www.heise.de/news/Microsoft-krallt-sich-Zugangsdaten-Achtung-vorm-neuen-Outlook-9357691.html) [ja sowieso schon](https://www.heise.de/news/Mac-Apps-telefonieren-nach-Hause-Apple-streicht-Opt-Out-Versprechen-9332632.html) [fast alles nach](https://www.heise.de/news/Feature-mit-Bug-Microsoft-Edge-telefoniert-besuchte-Seiten-nach-Hause-8980355.html) [Hause erzählen](https://www.heise.de/news/Studie-In-China-gekaufte-Android-Smartphones-telefonieren-haeufiger-nach-Hause-7488446.html).

-   

    ##### **22. Oktober 2023**

    Dass das Erleben und Anschauen von Kriegs- und Gewaltinhalten jeglicher Art seelische Spuren hinterlässt ist relativ offensichtlich und auch keine neue Erkenntnis. Neu ist die Unmittelbarkeit und die Qualität, mit der wir heute durch die digitalen Medien an den Krisen der Welt teilhaben können. Der Reiz, sich mit diesen Nachrichten zu konfrontieren steckt tief in uns:

    > Unser Gehirn ist immer auf der Suche nach Stimulation. Ich spreche gerne von unserem Steinzeithirn, weil die grundlegenden Mechanismen dieselben sind wie damals bei unseren Vorfahren. Das Gehirn hatte schon immer vor allem eine Aufgabe: den Körper, in dem es steckt, am Leben zu halten. Deshalb haben wir alle eine Vorliebe fürs Negative. Das ist evolutionsbiologisch total sinnvoll. Eine verpasste negative Nachricht kann womöglich den Tod bedeuten.

    Das wiederholte Ansehen solcher Darstellungen kann auf der einen Seite abstumpfend sein, im anderen Extrem zu einem starken Rückzugsverhalten führen, indem man ganz aufhört sich zu informieren. Auch das ist nicht weiter überraschend. Aber dass **der Stress, den ein Gewalt- oder Kriegsereignis bei Menschen auslöst, die (wiederholt) über die Medien davon erfahren, kurz- und langfristig z. T. sogar höher sein kann, als wenn man selber vor Ort gewesen wäre**, ist dann doch eine Meldung wert. Eine wissenschaftliche Erklärung dafür gibt es bisher nicht.

    [Das Interview mit der Neurowissenschaftlerin Maren Urner](https://www.nzz.ch/wissenschaft/welche-auswirkungen-haben-kriegsbilder-in-sozialen-medien-auf-unsere-psyche-ld.1761566) ist sehr informativ und lohnt sich in Gänze zu lesen.
:::
