project:
  type: website
  resources: 
   - "uploads"
   - "resources"
   - .htaccess

lang: de

website:
  title: "bewusstsein.digital"
  site-url: "https://www.bewusstsein.digital"
  favicon: resources/logo2.png
  navbar:
    background: primary
    logo: resources/logo2.png
    left:
      - href: empfehlungen/index.qmd
        text: Empfehlungen & Material
      - href: medienskript/index.qmd
        text: Skript
      #- seminar.qmd
      #- text: Downloads
      - href: faq/index.qmd
        text: Fragen & Tipps
      - href: blog.qmd
        text: Blog
        
      
    right:
      - href: about.qmd
        text: Über mich
      - icon: rss
        href: index.xml
  
  sidebar:
    - title: Empfehlungen
      contents: empfehlungen
    - title: Medienskript
      contents: medienskript
      
  page-footer:
    background: primary
    border: true
    center: 
      - href: impressum.qmd
      - href: datenschutz.qmd
        text: Datenschutz
      - href: about.qmd
        text: Kontakt
    right: |
      <span>Made with <img src="/images/Rlogo.png" style="width: 1rem;"/>, built with [Quarto](https://quarto.org/)</span>
      
  search:
    location: navbar
    type: overlay
  
  back-to-top-navigation: true
  page-navigation: true
  

bibliography:  medienskript/references.bib
#csl: springer-socpsych-brackets.csl


format:
  html:
    theme: [custom.scss, sandstone]
    css: styles.css
    filters: [resources/pandoc-quotes.lua]
    lang: de-DE
    backgroundcolor: "#FAF8F5"
    fontsize: 1.25rem
    linkcolor: "#325D88"
    link-external-newwindow: true
    link-external-icon: false
    toc-expand: true
    email-obfuscation: javascript
    canonical-url: true
    smooth-scroll: true
     
    grid: 
      gutter-width: 1.2rem
      
    include-in-header:
      - text: |
          <script async src="https://analytics.umami.is/script.js" data-website-id="a14cbb87-c4fb-4e31-a596-071da2ea3700"></script>

execute:
  freeze: auto
  
editor: visual

