---
title: "Empfehlungen"
toc: true
---

## Vorbemerkung

Im Sommer 2023 wurde bei der [AMWF](https://www.awmf.org/) die erste "Leitlinie zur Prävention dysregulierten Bildschirmmediengebrauchs in Kindheit und Jugend" veröffentlicht. Im Folgenden finden Sie die Empfehlungen dieser Leitlinie aufgeführt. Die Leitlinie adressiert folgende Risiken: Übergewicht / Schlafstörungen / Augenerkrankungen / Entwicklungsstörungen (Feinmotorik, Grobmotorik, Sprache) / Bindungsstörungen / Verhaltensstörungen / Internetnutzungsstörungen (Internetsucht) / Mobbing und Sexuelle Belästigung / Glücksspiel / Strahlung / Bildschirmmedien in der Schwangerschaft. Zudem gibt es einen Abschnitt zum Thema "Bildschirmmedien und Kinder mit besonderen Bedürfnissen"

Sie finden hier eine grafisch aufbereitete Kurzversion für Eltern:

```{=html}
<button class="btn btn-primary" data-umami-event="dl Elternversion"onclick="window.open('../../uploads/027-075eltern_S2k_Praevention-dysregulierten-Bildschirmmediengebrauchs-Kinder-Jugendliche_2023-09.pdf')"><i class="bi bi-file-earmark-pdf"></i> Download</button>
```
**Die hier dargestellten Informationen können jedoch keinesfalls die Lektüre der vollständigen Leitlinie ersetzen**:

Onlineversion: <https://leitlinie.bildschirmfrei-bis-3.de>

Original als PDF: <https://register.awmf.org/de/leitlinien/detail/027-075>

## Was ist die AWMF?

Bei der AWMF (Arbeitsgemeinschaft der Wissenschaftlichen Medizinischen Fachgesellschaften e. V.) werden [Leitlinien](https://register.awmf.org/de/start) zur Verbesserung der medizinischen Versorgung und Vermittlung von aktuellem Wissen publiziert, verantwortlich dafür sind Fachgesellschaften, die mit dem jeweiligen Thema Berührungspunkte haben. Im Fall der Medienleitlinie u. a. die

-   Deutsche Gesellschaft für Kinder- und Jugendmedizin e.V. (DGKJ)

-   Deutsche Gesellschaft für Suchtforschung und Suchttherapie e.V. (DG-Sucht)

-   Deutsche Gesellschaft für Sozialpädiatrie und Jugendmedizin e.V. (DGSPJ)

-   Gesellschaft für Seelische Gesundheit in der Frühen Kindheit (GAIMH)

-   Bundeszentrale für gesundheitliche Aufklärung (BZgA)

    und der

-   Berufsverband der Kinder- und Jugendärzt\*innen e. V. (BVKJ)
