---
toc: true
---

## Entwicklung von Kindern und Jugendlichen: Menschenkundliche Aspekte

Die Entwicklung des Kindes, so individuell sie im Einzelfall auch abläuft, lässt sich doch in bestimmte Phasen gliedern, in denen charakteristische Entwicklungsschritte passieren. Dem Sprachgebrauch der Waldorfpädagogik folgend werden die Hauptphasen hier als Jahrsiebte bezeichnet.

Schon in der frühen Kindheit lernen Kinder die drei menschlichsten Fähigkeiten überhaupt: Gehen, Sprechen und Denken. Sie müssen sich in ihrem Körper beheimaten und ein gesundes Verhältnis zu sich selbst und zu ihrer Umgebung entwickeln. Die Wahrnehmung der Welt ist aber nur über die Sinne möglich, weswegen deren möglichst differenzierte Ausbildung als Basis unerlässlich ist.[^1] Das Kind lebt im Rhythmus der Tagesstruktur und den Handlungen und Gewohnheiten der Erwachsenen und bildet sich daran. Die drei grundlegenden Seelenkräfte Denken, Fühlen und Wollen, bilden noch eine weitgehende Einheit. Diese drei Seelenkräfte stehen immer in einem gewissen Zusammenhang. Denken und Wollen sind wie zwei Pole, zwischen denen das Gefühl steht, mit dem wir unsere Gedanken begleiten oder unsere Willensimpulse umsetzen. Mit dem Älterwerden differenzieren sie sich voneinander, sind aber nicht verbindungslos (im Denken ist immer Wille nötig, sonst wäre eine gedankliche Verbindung gar nicht möglich). Die Bewusstseinsgrade sind jedoch sehr unterschiedlich, denn nur im Denken sind wir eigentlich vollständig wach. Das Gefühlsleben ist am ehesten mit einem Traumbewusstsein vergleichbar und im Willen herrscht in etwa so viel Bewusstsein wie im Tiefschlaf. Der Wille lässt sich zwar durch das Denken zu einem bestimmten Teil steuern, die Willenstätigkeit, die beispielsweise in der Körpermotorik vonnöten ist, um einen Arm zu heben, entzieht sich allerdings unserer direkten Kontrolle. Alle Seelenkräfte sind seit der Geburt im Kind veranlagt. Der Wille ist sicherlich am deutlichsten in den zunächst noch sehr unkoordinierten Bewegungen des kleinen Kindes sichtbar. Nach und nach werden die Bewegungen wie gedanklich durchsetzt, sie bekommen Richtung und Ziel. Die Gedankenkräfte selber fließen aber hauptsächlich in die Gestaltung des physischen Leibes ein.[^2]

[^1]: Vgl. @hübner2015 S. 289 ff.

[^2]: Vgl. @steiner1967 S. 189 ff.

Mit dem Zahnwechsel tritt das Kind in eine neue große Lebensphase ein. Die Kräfte, die es bisher benötigt hat um vor allem seinen Leib zu bilden, werden jetzt frei und können nun für das Erlernen von Kulturtechniken, wie Schreiben und Lesen und erste sportliche und handwerkliche Tätigkeiten eingesetzt werden. Dies betrifft auch die Unterrichtung an einem Musikinstrument. Der Zahnwechsel ist deswegen ein gutes Anzeichen, weil die Zähne aus dem härtesten Material bestehen, was im Körper gebildet werden muss. Sie kommen daher zum Schluss der grundlegenden Ausbildung des physischen Leibes. Natürlich kann ein Kind schon früher Lesen und Schreiben lernen, oft wollen sie das sogar, es besteht aber immer die Gefahr, dem Kind Kräfte zu entziehen, die an anderer Stelle noch benötigt werden. Dies kann in späteren Jahren auch Auswirkungen auf die gesundheitliche Konstitution haben.

> Die sie umgebenden Erwachsenen und ihre Sicht auf die Welt spielen für die eigene Weltsicht der Kinder eine entscheidende Rolle. Das Gefühlsleben tritt nun mehr in den Vordergrund und auch das Denken verändert sich, jedoch in einem vielmehr bildhaften als abstrakten Charakter.[^3]

[^3]: @steiner1965 S. 53

Daher hat es keinen Sinn, in diesem Lebensalter ihm etwas durch den Intellekt beibringen zu wollen. Alles muss in dieser Zeit auf das Gefühl hin orientiert sein; denn das Gefühl nimmt das Bildhafte auf, und auf das Bildhafte, auf das Zusammenstimmen von Einzelheiten hin ist das Kind in diesem Lebensalter organisiert.\
Die Kinder merken, dass sie Einzelwesen sind, die sich selber beobachten können. Dies wird besonders um das neunte Lebensjahr herum deutlich, wenn sich die Kinder nochmal spürbar aus der vorher erlebten Einheit distanzieren. Neue Fragen tauchen auf, nach dem Tod, also der Endlichkeit des Lebens, oder nach ihrer wirklichen Herkunft. Dies ist oft eine erste wirkliche Gefühlskrise.[^4]

[^4]: Vgl. @setzer1992 S. 33

Die Pubertät kennzeichnet den Übergang in das dritte Jahrsiebt. Mit der Geschlechtsreife treten aber noch viele weitere körperliche und seelische Reifungsprozesse auf. So entwickeln sich nun auch Denken, Fühlen und Wollen zu eigenständigen seelischen Betätigungsfeldern. Rudolf Steiner prägte für diesen Entwicklungsschritt den Begriff der „Erdenreife". Nun ist auch die Zeit, das logische, abstrakte, formale und individuelle Denken einzuführen.[^5] Begrifflichkeiten sollten den Jugendlichen in diesem Alter nicht vorgegeben werden, sondern sie sollten die Möglichkeit haben, sich wahrnehmend und handelnd mit einem Thema auseinanderzusetzen um es danach beschreiben zu können. Dieser Weg über die Erfahrung, in einem begleiteten, ergebnisoffenen Prozess, fordert einen Bewusstseinsprozess über die Erinnerung, an dessen Ende die Begriffe gemeinsam erarbeitet werden können. Dieser, von Rudolf Steiner beschriebene Weg des Denkens,[^6] von Schluss (Wahrnehmung) über das Urteil (individuelle Verbindung) zum Begriff (Erkenntnis), der explizit auch die Verarbeitung im Schlaf berücksichtigt, erstreckt sich nicht nur über einzelne Unterrichtseinheiten, sondern in größeren Bögen auch über die gesamte Schullaufbahn.[^7]

[^5]: Vgl. ebd. S. 36 f.

[^6]: Eine ausführliche Beschreibung findet sich in @steiner1993 9. Vortrag.

[^7]: Vgl. @struwwel2019 S. 8 f.
