---
toc: true
---

## Eigenschaften der Medien und psychologische Wirkungen

Die Medien haben die prinzipielle Eigenschaft, die in ihnen enthaltenen Informationen zu zergliedern. Schon die Schrift analysiert die Sprache in einzelne Laute und teilt ihnen bestimmte Symbole zu. Im klassischen Film wird die Bewegung durch die schnelle Wiedergabe von vielen hintereinander aufgenommen Einzelbildern erzeugt. Ein Digitalfoto besteht aus Millionen einzelner Bildpunkte und akustische Signale werden zeitdiskret abgetastet, so dass die gemessenen Werte digital verarbeitet werden können. Dies wirkt sich aber auch auf die Inhalte aus, da sie immer nur aus dem Ganzen herausgelösten Einzelheiten zeigen. Die Welt präsentiert sich so in unzähligen Einzelinformationen, dies ist am Beispiel einer Nachrichtensendung gut nachzuvollziehen, die der Mensch nur durch seinen Wissenshintergrund in Zusammenhang bringen kann. So wird dann auch deutlich, dass aus Informationen erst dann Wissen werden kann, wenn sie in einem übergeordneten Rahmen in Beziehung gebracht werden können.[^1]

[^1]: Vgl. @hübner2015 S. 273 ff.

Ein schönes Beispiel zur Wirkungsweise des Computers ist in einem Lehrbuch zum Unterricht der Computertechnik von Manfred von Mackensen dargestellt:[^2] Wenn man den Begriff „sieben" vernimmt, so ist dieser zunächst nahezu inhaltsleer. Hört man dann beispielsweise „sieben Tage", „sieben Euro", oder „sieben gegenüber sechs", so entsteht eine Denkbewegung in eine bestimmte Richtung. Wenn die Sieben also in einem bestimmten Zusammenhang auftaucht, kann man weitere Fragen oder Vermutungen dazu stellen und Vorstellungsbilder entwickeln. Mit dem Inhalt bekommt die starre Identität „sieben" eine Richtung, eine fließende Bewegung, die mit dem wechselnden Zustand der menschlichen Seele einhergeht und anderes hinzunimmt. Geht man den Weg zurück, die Zahl wird wieder aus den bewegten Inhalten gelöst und frei von Zeit und Ort und jedem persönlichen Bezug beispielsweise auf einen Zettel geschrieben und mit anderen Zahlen oder Begriffen, die dort ebenfalls stehen und genauso erstarrt sind, in verschiedene Kombinationen gebracht, so kommt man mit dem Bewusstsein näherungsweise an einen Computervorgang mit seinen formalen, logischen Formen ohne Erlebnisinhalt heran. Der Mensch kann nun ebenfalls diese Zahlen oder Begriffe nutzen und etwa mit ihnen rechnen. Dies ist eine willentliche Verstandestätigkeit aus einer bestimmten Bestrebung heraus, die unsichtbar vonstattengeht, mit dem Ziel ein passendes Ergebnis zu der vorangehenden Fragestellung zu liefern. Diese Willenstätigkeit wird nun vom Computer ersetzt und zwar von dem, was der Entwickler von seinem Willen in den Algorithmen der Maschine hinterlassen hat.

[^2]: Vgl. @ursprüng1990 S. 89 f.

> Infogeldessen wird eine bestimmte Form von menschlichem Willen, d. h. eine bestimmte Form der Ergreifung des physischen Leibes, hier des Gehirns, an der Maschine nicht mehr benötigt. Das verringert das willenshafte und damit irdische (physische) Hervortreten des Menschen.[^3]

[^3]: @ursprüng1990 S. 90

Angefangen beim Taschenrechner greift also der Computer in den Willen im Denken ein (Verstandesersatz), davon ausgehend jedoch über auf äußere Handlungen (Automation). Dies ist heute für uns so normal geworden, dass wir kaum noch darüber nachdenken, jedoch wird mit diesen Anwendungen mehr und mehr der individuelle und moralische menschliche Weltbezug ersetzt.

Der Mensch braucht diese starren Begriffe. Zahlen, Maße, Zeiten, aber auch Vorschriften und Gesetze sind für das äußere Leben unerlässlich. Sein Inneres lernt er jedoch durch offene Begriffe, wie Schönheit, Freiheit, Anstrengung, Gewissen oder auch der Qualität einer Farbe, also durch Begriffe, die sich auch mit Erfahrungsinhalten nähren, zu ergreifen. Der Computer ist in der Lage, mit den festen und immer weiter zersplitterten Begriffen und formalen Eingaben unglaublich schnelle Rechenoperationen durchzuführen. Beim Umgang mit ihm überwiegt aufgrund dessen jedoch das monokausale, analytische Denken. Ohne Gegengewicht, verschieben sich die geistigen Kräfte und Fähigkeiten dann immer mehr in eine formale Richtung.[^4]

[^4]: Vgl. @ursprüng1990 S. 90

Dies hat noch einen weiteren Umstand zur Folge. Eine Beobachtung ist nämlich, dass man, gerade bei komplexeren Anwendungen, einmal gelernte Benutzungsroutinen sehr schnellwieder vergisst. Dies liegt an der beschriebenen Einseitigkeit der formalen Begriffe, die sich kaum durch Tätigkeit verinnerlichen lassen. Zudem sind die ausgeführten Tätigkeiten, egal in welcher Anwendung, im Prinzip immer dieselben: Tastaturbefehle, Mausbewegungen oder Wischgesten. So werden aber keine bleibenden Eindrücke, keine motorischen Erinnerungen geschaffen, die sich mit den rein kognitiven Eindrücken verbinden können, da sich alles überlagert. Mackensen beschreibt dieses Vergessen jedoch als ein Zeichen, welches eigentlich von seelischer Gesundheit zeugt.[^5]

[^5]: Vgl. @ursprüng1990 S. 90

\
