---
toc: true
---

## Mediennutzung von Kindern und Jugendlichen

Kinder wachsen heute größtenteils schon zu Hause in einem, im wahrsten Sinne des Wortes, multi-medialen Umfeld auf. Die Ausstattung der Haushalte hat bei Fernseher, Computer/Laptop, Internetzugang und Smartphone/Handy einen Sättigungszustand erreicht. Die individuelle Ausstattung der Kinder und Jugendlichen mit eigenen Geräten wird, angefangen beim Handy/Smartphone, welches schon die Hälfte aller Kinder zwischen 6 und 13 Jahren besitzen, mit steigendem Alter ergänzt durch Laptop/Computer und eigenem Fernseher. Vor allem bei den Jungen gewinnen dann auch die Spielkonsole und der Computer an Bedeutung.[^1]<sup>,</sup>[^2]

[^1]: Vgl. @feierabend2019 S. 8-10

[^2]: Vgl. @feierabend2018 S. 8-10

### Medienbiographie und Mediennutzung

Der Einstieg in die Medienwelt beginnt für die Kinder im Durchschnitt mit etwa vier Jahren. Dann kommen die Erstgeborenen mit Fernsehen und Radio in Kontakt (siehe @fig-einstiegsalter). Da in der FIM-Studie 2016 (Familie, Interaktion, Medien) nach dem Alter der ersten selbstbestimmten(!) Nutzung gefragt wird, ist davon auszugehen, dass der tatsächliche Erstkontakt wesentlich früher ist. Mit sieben Jahren kommen dann plattform-übergreifend digitale Spiele hinzu und mit acht der Computer. Ein Jahr später haben die Kinder im Schnitt auch Umgang mit dem Internet und dem Smartphone. Dabei sind die Kinder von jüngeren Eltern häufig früher mit elektronischen Medien beschäftigt als von älteren Eltern. Die Studie zeigt auch, dass sich das Durchschnittsalter zur Erstnutzung im Vergleich zur vorigen Erhebung aus dem Jahr 2011 verringert hat.[^3]

[^3]: Vgl. @feierabend2017 S. 58

![Durchschnittsalter des Erstgeborenen bei der ersten Mediennutzung[^4]](images/einstiegsalter.jpg){#fig-einstiegsalter}

[^4]: @feierabend2017 S. 58

[^5]: @feierabend2017 S. 58

In der KIM-Studie 2018 (Kinder, Internet, Medien) wurden Kinder im Alter von 6 bis 13 Jahren sowohl nach Themen, die sie interessieren befragt, als auch nach ihren Freizeitaktivitäten. Das Thema Freundschaft steht dabei an oberster Stelle der Interessen (93 %), gefolgt von Sport, Handy/Smartphone und der Schule (jeweils 69 %). Auch an Musik (64 %) und dem Thema Bücher/Lesen (50 %) sind die Kinder interessiert (Die Zahlen beziehen sich auf die Antwortoptionen: „finde ich sehr interessant", „finde ich interessant").[^6] Auf die Freizeitaktivitäten geschaut, geben 96 Prozent aller befragten Kinder an, mindestens einmal in der Woche fernzusehen (egal über welchen Verbreitungsweg), täglich oder fast jeden Tag 74 Prozent. Freunde treffen, spielen, sowie Hausaufgaben machen und lernen ist auch für etwa 90 Prozent der Kinder mindestens einmal in der Woche relevant. Unter den liebsten Freizeitaktivitäten sind Freunde treffen, gefolgt von draußen spielen und fernsehen die drei am häufigsten genannten.[^7]

[^6]: Vgl. @feierabend2019 S. 5

[^7]: Vgl. @feierabend2019 S. 11-14

![Mediennutzung: Mache ich\...[^8]](images/mediennutzung.jpg){#fig-mediennutzung}

[^8]: @feierabend2019 S. 15

[^9]: @feierabend2019 S. 15

Auffällig bei der Befragung zur Mediennutzung ist, dass die Hälfte der Kinder angeben, eher alleine fernzusehen (6-7 Jahre 43 %). Auch beim Spielen auf dem Handy/Smartphone und beim Surfen im Internet, sitzen die Kinder, die es schon machen, meistens alleine vor dem Bildschirm. Am zweithäufigsten wird oft die Nutzung mit Freunden genannt, die Elternsind oft sehr wenig in die Mediennutzung involviert. Klar ist, dass mit steigendem Alter die Mediennutzung immer autonomer erfolgt, jedoch ist gerade bei den jüngeren Kindern fraglich, inwieweit die Erwachsenen so einen Überblick über den zeitlichen Umfang und die Inhalte der Tätigkeiten ihrer Kinder mit digitalen Medien haben.

Werden die Eltern diesbezüglich nach Familienregeln gefragt, geben 57 Prozent an, Vereinbarungen zur Nutzung von Serien und Filmen zu haben. Dauer (50 %) und Inhalt (47 %) von digitalen Spielen werden ebenso wie die Nutzung von Inhalten im Internet (47 %) in den Familien reglementiert. Der Umgang mit dem Smartphone wird mit 32 Prozenterstaunlich wenig in den Familienregeln berücksichtigt. Dies spiegelt sich auch in den Antwortender Kinder wider (siehe Abbildung 4). So gibt es bei jedem dritten Jugendlichen zwischen 12 und 19 Jahren keine Regeln zur Smartphonenutzung, obwohl inzwischen fast jeder eines besitzt.[^10]

[^10]: Vgl. @feierabend2017 S. 18 f.

![Familienregeln: es gibt Regeln\...[^11]](images/familienregeln.jpg){#fig-familienregeln}

[^11]: @feierabend2017 S. 19

[^12]: @feierabend2017 S. 19

Bei den Jugendlichen (12-19 Jahre) steht an oberster Stelle der täglichen Mediennutzung das Smartphone (94 %), gefolgt von der Benutzung des Internets (91 %) und dem Hören von Musik (84 %). 39 Prozent der befragten Jugendlichen gaben an, täglich oder mehrmals in der Woche in ihrer Freizeit ein gedrucktes Buch zu lesen (nicht für die Schule). Dieser Wertliegt seit 20 Jahren immer um 40 Prozent, wobei Geschlecht und Bildungsgrad einen starken Einfluss auf die Lesehäufigkeit haben (Mädchen lesen häufiger als Jungen und Jugendlichemit formal höherem Bildungsniveau lesen ebenfalls mehr). Das E-Book hat nur einen sehr geringen Anteil. Jeder Zehnte liest zudem täglich die Tageszeitung auf Papier.[^13] Bei der Freizeitgestaltung ohne Medien haben Freunde, Sport und Familienunternehmungen die größte Bedeutung. Jeder fünfte Jugendliche gab an, mindestens mehrmals in der Woche selber Musik zu machen. Hier sind zwar die Gymnasiasten etwas aktiver als Jugendlichemit formal niedrigerem Bildungsniveau und die Mädchen etwas mehr als die Jungen, aber dieser Wert hat insgesamt in den letzten Jahren leicht zugenommen.[^14]

[^13]: Vgl. @feierabend2018 S 13. f. und 18 ff.

[^14]: Vgl. @feierabend2018 S. 11 f.

### Einhaltung von empfohlenen Nutzungszeiten

In der zwischen 2016 und 2017 durchführten BLIKK-Studie, die vor allem das Ziel hatte zu prüfen, inwieweit sich Entwicklungsauffälligkeiten bzw. -störungen bei Kindern und Jugendlichen im Zusammenhang mit der Nutzung elektronischer Medien zeigen lassen, wurden unter anderem auch die Mediennutzungszeiten erfragt. Die Ergebnisse wurden dann mit den empfohlenen Mediennutzungszeiten für Kinder der Bundeszentrale für gesundheitliche Aufklärung (BZgA)[^15] verglichen. Die Studie wurde im Rahmen der Früherkennungsuntersuchungen in verschiedenen kinder- und jugendärztlichen Praxen deutschlandweitdurchgeführt. Insgesamt sind 5.573 Kinder befragt worden, davon 2.632 Jungen und 2.451 Mädchen. Bei 490 Kindern wurde kein Geschlecht angegeben. Bis zum zehnten Lebensjahr der Kinder gaben die Eltern Auskunft zu den Nutzungszeiten. In Abbildung 5 werden die relativen Häufigkeiten der Kinder und Jugendlichen aufgeführt, deren Nutzungszeitenüber den Cut-off-Werten der BZgA liegen. In der Auswertung wurde für die Altersgruppe 2-8 Jahre 30 Minuten und für die Altersgruppe 9-14 Jahre 60 Minuten als Cut-off-Wert zugrunde gelegt. Dabei wird deutlich, dass die Fernsehnutzungszeiten in der jüngsten Altersgruppe von der Hälfte der Kinder überschritten wird, in der Altersgruppe7-8 Jahre sind es sogar rund 77 Prozent. In der Gruppe der 9-14-Jährigen nimmt dieser Wert wieder ab, dafür rücken jetzt Smartphone und Internet in den Fokus.[^16]

[^15]: @bundeszentralefürgesundheitlicheaufklärung2015

[^16]: Vgl. @blikk-me2017 S. 3 ff.

![Gegenüberstellung Empfehlungen der täglichen Gesamtnutzungszeiten und die relativen Häufigkeiten der Nutzungszeiten elektronischer Medien in der BLIKK-Stichprobe, die über den empfohlenen Cut-off-Werten liegen[^17]](images/blikk-medienzeiten.jpg){#fig-blikkmedienzeiten}

[^17]: @blikk-me2017 S. 5

[^18]: @blikk-me2017 S. 5
