---
toc: true
---

## Von der Medienkompetenz zur Medienmündigkeit

Der Begriff der Medienkompetenz ist heute in aller Munde, wenn es um Diskurse zur Medienerziehung geht. Dabei wird er ebenso schwammig wie weitläufig definiert und reduziert die Fähigkeiten im Umgang mit digitaler Technik oft auf das Befolgen von (Bildschirm-) Anweisungen und korrekter Bedienung.[^1] Dies wurde auch von der Politik erkannt und so entstand im Rahmen der Enquete-Kommission „Internet und digitale Gesellschaft" folgende Zielvorstellungen für die Vermittlung von Medienkompetenz:[^2]

[^1]: Vgl. @bleckmann2012 S. 29 f.

[^2]: @jarzombek2011 S. 32

-   Grundlagenkenntnis: Beherrschen der Kulturtechniken Schreiben und Lesen,

-   technische Fähigkeiten (Umgang mit Hard- und Software, Grundverständnis vom Aufbau des Internets, Grundkenntnisse im Programmieren etc.), die vor allem auf das Verstehen von Zusammenhängen und die Befähigung zum Selbstlernen abzielen,

-   kritisches Hinterfragen von Inhalten (Quellen einschätzen, Absichten von Sendern erkennen, Sensibilisierung für Werbebotschaften etc. Dies ist ebenso für den Umgang mit klassischen Medien wichtig -- zum Beispiel Zeitungsprojekte, die auch für den Umgang mit Onlineinhalten positive Effekte haben können.),

-   kompetenter Umgang mit der Informationsflut (Grundverständnis der Funktionsweise von Suchmaschinen; Vermeiden einseitiger Informationsauswahl, stattdessen sinnvolle Nutzung der Meinungsvielfalt im Netz),

-   Risikobewusstsein (Kostenfallen, Datenschutz, Betrug, Missbrauch),

-   Kreativität beim Umgang mit und dem Schaffen von Inhalten, aber auch Grundsätzliches wie Werte und soziale Kompetenz (Problembewusstsein für Cyber-Mobbing; sich verantwortungsvoll bewegen in einem mehr oder weniger anonymen Raum etc.),

-   Informationskompetenz, also die Fähigkeit, Informationen zu bewerten und zu nutzen, Unbedeutendes auszusortieren, sowie einschätzen zu können, wie viele Informationen situationsbezogen angegeben werden müssen/können,

-   Befähigung zum Erstellen eigener Inhalte (Webseite, Blog, Film, Musik, eventuell Software-Entwicklung).

Die Kompetenzen sollen dabei technologieneutral und unabhängig von Herstellern vermittelt werden. Demnach wäre eine Medienkompetenz erst dann gegeben, wenn man z. B. in der Lage ist, ausgehend von dem Textverarbeitungsprogramm, an dem man unterrichtet wurde, in einem beliebigen Textsatzprogramm mit vertretbarem Zeitaufwand selbstständig beispielsweise Serienbriefe zu erstellen.[^3]

[^3]: Vgl. @jarzombek2011 S. 32

Von etlichen dieser Ziele sind wir selbst als Erwachsene noch weit entfernt, es scheint also nur folgerichtig, dies in der Schule, möglichst von Anfang an, zu lehren.

Demgegenüber setzt die Medien- und Gesundheitspädagogin Paula Bleckmann den Begriff der „Medienmündigkeit". Sie hat dazu gleich mehrere Definitionen entwickelt:

> Medienmündig werden bedeutet zuallererst, nicht die Kontrolle über unsere kostbare Lebenszeit zu verlieren. Medienmündig sein heißt, souverän über die eigene Zeit zu verfügen \[\...\]. Unter Zeitsouveränität verstehe ich die freie Entscheidung, wie viel Zeit wir überhaupt mit Medien verbringen und damit anderen Tätigkeiten entziehen möchten.[^4]

[^4]: @bleckmann2012 S. 14

Oder etwas komplizierter ausgedrückt:

> Medienmündig ist, wer die Entscheidung, was er mit Medien macht und was lieber ohne Medien, auf dem Wissen darüber aufbaut, was Medien langfristig mit Menschen machen, die etwas mit Medien machen.[^5]

[^5]: @bleckmann2012 S. 135

Es geht also mit dem Begriff der „Mündigkeit" um Selbstbestimmtheit und Autonomie des Menschen in einem bestimmten Lebensbereich, in diesem Fall im Bereich der digitalen Medien. Solange Kinder noch nicht in der Lage sind, ihre langfristigen Ziele und Bedürfnisse in der Art zu reflektieren, dass sie mögliche Nachteile oder sogar Gefährdungen ihrer persönlichen Entwicklung erkennen können, sind sie auf Hilfe und Schutz von Erwachsenen angewiesen. Die Entwicklung zur Selbstbestimmtheit, und somit zur Mündigkeit, geschieht durch einen Reifungsprozess, so dass das Kind im Laufe der Zeit immer mehr seine Urteilsfähigkeit schult und immer weniger auf den Erwachsenen angewiesen ist. Mit Medienmündigkeit ist also auch die Fähigkeit gemeint, Chancen und Risiken der unterschiedlichen Medien in Bezug auf Befriedigung der eigenen Ziele und Bedürfnisse, abschätzen zu können und die Geräte dementsprechend einzusetzen oder abzuschalten.[^6]

[^6]: Vgl. @bleckmann2012 S. 33 f.

## Turm der Medienmündigkeit

Wie wird nun diese Medienmündigkeit erreicht? Paula Bleckmann entwickelt dazu das Bild eines Turms (siehe Abbildung 6), dessen Fundament die sensomotorische Integration, also die Verknüpfung von Sinneswahrnehmung und Bewegung ist. Diese Basis muss so stabil sein, dass sie den ganzen Turm trägt. Diese Basis-Fähigkeiten können aber nur im realen Leben erlernt werden und werden von der Interaktion mit digitalen Medien, die ja oft nur minimale Bewegungen erfordern, stark behindert. Genauso verhält es sich mit den Kommunikationsfähigkeiten, der zweiten Stufe des Turms. Auch diese können kleine Kinder nur mit Hilfe und unmittelbarem Kontakt von und mit anderen Menschen erlernen, denn dazu gehört neben Sprechen, Schreiben und Lesen auch Gestik und Mimik und besonders für kleine Kinder: Körperkontakt. Im dritten Stock geht es um die Entwicklung der eigenen Gestaltungskraft, etwas auf die Beine zu stellen. Phantasie ist dazu wichtig, auch das Überwinden von Hindernissen und das (Noch-)Nicht-Können auszuhalten, also das Erlernen von Frustrationstoleranz. Dies sollte sich aus dem kindlichen Spiel entwickeln, schöpferisch werden beim Malen, in der Musik, etwas zu bauen, eine Geschichte zu schreiben oder Theater zu spielen. Im Bereich der Medien könnte dann zum Beispiel mit älteren Kindern ein Hörspiel oder eine Radiosendung erstellt werden, ein Film gedreht oder etwas programmiert werden. Diese „Medienproduktionen" sollten einem reinen Konsum von Medien im Idealfall vorangehen, damit im nächsten Schritt die Möglichkeit das Wahrgenommene zu verstehen, zu verarbeiten und weiterzudenken geschaffen wird. Diese Rezeptionsfähigkeiten (4. Stock) sollten ebenfalls in der realen Welt geübt werden: Geschichten hören und selber lesen, musizieren, Zeitung lesen und im Lexikon recherchieren. Dann erst gemeinsam Filme anschauen und darüber ins Gespräch kommen und das Internet mit seinen Komponenten nutzen. Der Begriff der Medienkompetenz findet sich also im dritten und vierten Stockwerk des Turms, nämlich genau da, wo der Umgang mit elektronischen Medien wirklich angebracht ist.

Das letzte Stockwerk des Turms ist die Fähigkeit kritisch zu reflektieren. Dies meint sowohl das eigene Medienverhalten betrachten, einschätzen und beurteilen zu können und daraus Konsequenzen für das eigene Handeln zu ziehen, aber auch auf das große Ganze zu schauen und Chancen und Risiken von Technologien abschätzen zu können. Diese Fähigkeiten bilden sich erst im Jugendalter und müssen auch von Erwachsenen immer weitergedacht werden. Elternhaus und Schule haben also die Verantwortung zunächst die Kinder vor den Gefahren und Verführungen durch Fernsehen und Internet zu schützen und sie dann, im Jugendalter, Schritt für Schritt im Umgang mit elektronischen Medien zu begleiten. Dies hat zur Folge, dass gelernt werden kann wirklich auszuwählen, welche Technik sich gerade am besten dafür eignet, das aktuelle Bedürfnis zufrieden zu stellen und ob es dafür auch medienfreie Alternativen gibt. Dazu ist es aber nötig, wirkliche Alternativen kennengelernt zu haben und ein Bewusstsein darüber, dass z. B. der Fernseher nur sehr kurzfristig (falls überhaupt) zur Erholung dient und ein Spaziergang oder ein Café-Besuch mit Freunden, auch wenn es zunächst vielleicht etwas mühsamer erscheinen mag, sehr viel nachhaltiger der Entspannung dient. Diese Selektionsfähigkeit zieht sich über den ganzen Turm der Medienmündigkeit und hält ihn wie ein Spanngurt zusammen.[^7]

[^7]: Vgl. @bleckmann2012 S. 89-108

![Turm der Medienmündigkeit[^8]](images/turm-medienmuendig.jpg){#fig-turm-medienmuendig}

[^8]: @bleckmann2012 S. 107

[^9]: @bleckmann2012 S. 107
