---
toc: true
---

## Chancen und Risiken der Medien

Kaum ein Thema wird gegenwärtig so kontrovers diskutiert, wie die Auswirkungen von digitalen Medien auf Kinder und Jugendliche. Experten streiten sich genauso darüber, wie Eltern ratlos vor den Erziehungsaufgaben stehen. Neben allem praktischen Nutzen, die die Medienlandschaft heutzutage bietet, stehen nämlich immer die eingangs erwähnten Fragen des Was, Wann, Wie und Wie lange, die zu stellen sich sicherlich als Erwachsener auch immer wieder lohnt. Das kritische Hinterfragen der Medienangebote ist daher unbedingt erforderlich.

### Chancen

Die Medien bieten mittlerweile demjenigen, der sie sinnvoll zu nutzen weiß, unzählige Möglichkeiten der Wissensaneignung, Kommunikation und Verständigung. Angefangen bei der Schrift, präsentieren uns die Medien durch Bild, Ton und Film die Erfahrungen und Gedanken anderer Menschen und durch das Internet haben wir die Voraussetzung, ein globales Bewusstsein zu entwickeln. Das Wissen ist heute nahezu überall und frei verfügbar, auch Kunstwerke und Musik jedweder Art stehen jedem interessierten Menschen zur Verfügung. Mit dem Mobilfunk wurde die fernmündliche Kommunikation ortsunabhängig, mit der Entwicklung des Internets wurden räumliche und zeitliche Barrieren der Vernetzung fast vollständig überwunden. Man ist heute in der Lage sich der ganzen Welt mitzuteilen. Der Mensch muss allerdings den Willen entwickeln, diesen Angeboten Interesse entgegenzubringen und sich ein Verständnis erringen, damit sich die Potenziale der Medien entfalten können. Dies gilt in besonderem Maße auch für die Kommunikation und die (Selbst-)Darstellung im Internet.[^1] Zudem muss der Zurücknahme der äußerlichen, körperlichen Aktivität, die bei gedanklichen Tätigkeiten eintritt, eine verstärkte innere Betätigung entgegengesetzt werden. Diese innere Regsamkeit ist aber bei der Nutzung von audiovisuellen Medien nicht automatisch gegeben, wie zum Beispiel beim Lesen eines Buches, sondern erfordert eine aktive Anstrengung.[^2]

[^1]: Vgl. @hübner2015 S. 195-201

[^2]: Vgl. @hübner2015 S. 304

### Risiken

Eine grundlegende Eigenschaft der Computernutzung ist die, dass die Bedienung meist nur einen minimalen Bewegungsaufwand an Maus und Tastatur, Controller oder Wischgesten am Smartphone benötigt. Die Aufnahme der Inhalte geschieht fast ausschließlich über Auge und Ohr. Der übrige Leib ist nahezu ruhiggestellt, da man außerdem meistens sitzt oder liegt. Dies belastet die Gelenke, Muskeln und Bänder von Händen, Armen und Hals und vor allem auch die Augen überproportional. Inzwischen ist auch bekannt, dass das Lesen auf Papier die Augen weniger anstrengt als auf dem Bildschirm. Der Mangel an körperlicher Aktivität fördert zudem Übergewicht bis hin zur Fettleibigkeit. Gerade bei Kindern, die ja noch im Wachstum sind, wächst sich das zu einem ernsten Problem aus. In der Berufswelt gibt es von der richtigen Aufstellung der Geräte über das richtige Mobiliar bis hin zu Beleuchtungsaspekten, vorgeschriebenen Pausen und (augen-) ärztlichen Untersuchungen, längst dutzende Vorschriften zur Ergonomie an Bildschirmarbeitsplätzen. In der Schule werden diese häufig gar nicht berücksichtigt.[^3]

[^3]: Vgl. @cordes2002 S. 29-39

Die Medien üben zudem einen ungeheuren Sog, nicht nur auf Kinder und Jugendliche, aus. Schon in den siebziger Jahren des vorigen Jahrhunderts beschrieb der Informatiker und Computerkritiker Joseph Weizenbaum das teilweise zwanghafte Verhalten von Programmierern.[^4] Mechanismen, die Menschen vor dem Bildschirm und in bestimmten Anwendungen oder Spielen fesseln, sind heute weit verbreitet, man kann sie in Studiengängen wie „Angewandte Konsumenten Psychologie" sogar lernen. Verhaltensformer nennen sich dann Menschen, die gewohnheitsbildende Produkte und Algorithmen gestalten. Facebook setzte sie von Anfang an ein. Ein schier endloser Fluss an Beiträgen von Freunden, Nachrichten und Unterhaltungsinhalten, dazu digitale Streicheleinheiten in Form von sogenannten Likes, Herzen, Smileys oder Kommentaren. Alles sicherlich optisch und akustisch aufeinander abgestimmt. Häufige Auslöser sind Langeweile oder Einsamkeit der Nutzer. Damit werden sie dazu gebracht, sich immer öfter einzuloggen und immer mehr Zeit bei den Angeboten zu verbringen. Bei Computerspielen ist es ähnlich. Viele von ihnen sind de facto nie zu Ende, zudem werden immer wieder Erweiterungen kreiert. Mit einem wohldosierten Belohnungssystem werden die Spieler bei der Stange gehalten und je mehr Zeit man in das Spiel investiert, umso besser wird man. Man kann sich jederzeit einklinken, da das Spiel immer online ist und so gibt das Spiel irgendwann den Lebensrhythmus vor. Die Potenziale dieser nicht-stofflichen Süchte sind enorm. Die Folge davon ist, dass bereits fast ein Drittel der 18- bis 24-Jährigen Jugendlichen in der USA süchtig nach irgendetwas Digitalem sind. Die Internet Addiction Disorder (Onlinesucht) und die damit verbundene Gaming Disorder sind zwar noch zu wenig erforscht, um offiziell als Krankheit zu gelten, die Folgen wie Konzentrations- und Schlafstörungen, Vereinsamung und Depression und der Leistungsabfall, vor allem auch in der Schule, sind jetzt schon gravierend.[^5]

[^4]: Vgl. @weizenbaum1978 S. 155-179

[^5]: Vgl. @kreye2019

Der Computer und das Internet sind Medien für Erwachsene. Ihre Funktionsweise und vor allem die Inhalte sind auf ein rationales kognitives Denken zugeschnitten und bedürfen einer kritischen Beurteilung. Sicherlich gibt es unzählige, auf Kinder zugeschnittenen Angebote, oft gespickt mit jeder Menge Werbung, deren Absicht sie noch nicht erkennen können, aber häufig ist der Weg ins offene Netz nicht allzu schwierig. Dort müssen die Kinder vor Inhalten, die ebenso frei zugänglich sind, die sie aber überfordern oder sogar traumatisieren können, besonders geschützt werden. Wenn sie dann ihre eigenen Geräte benutzen und selbstständig in der Medienlandschaft unterwegs sind, kommen Gefährdungen wie zum Beispiel Cyber-Mobbing und Internetkriminalität hinzu. Hier ist viel pädagogische Arbeit zu leisten.

## Was digitale Medien nicht vermitteln können

Seit die Computer auf dem Vormarsch sind, wird immer wieder über deren Einsatz in Schulen diskutiert. Zu groß scheinen die Vorteile um sie nicht vor allem für das selbstbestimmte und selbstgesteuerte Lernen einzusetzen und das, gerade für die jüngeren Kinder, so spielerisch wie möglich. Das Spiel, was Kinder so begeistert, wird in eine digitale Lernumgebung integriert und kann somit gleichzeitig der Wissensvermittlung dienen. Selbstgesteuertes Lernen kann aber, wie der Begriff schon sagt, nur von einem *Selbst* initiiert werden, Medien können dabei von Nutzen sein, es aber auch behindern. Voraussetzung ist in jedem Fall Interesse und der Wille zum Durchhalten der Lernprozesse. Das Interesse der Kinder wird aber gerade am häufigsten durch die Menschen in ihrer Umgebung angeregt, Lehrer, Erzieher, Eltern und andere Menschen, die sich Kinder aufgrund der Art und Weise ihrer Tätigkeiten zum Vorbild suchen. Aus diesem Interesse kann dann auch wirklich etwas Neues entstehen, da man im gemeinsamen Tun die Möglichkeit hat, etwas zu kreieren, was nicht vom Programm vorgesehen ist. Dies kann sogar am Ende real vor einem stehen und ist benutzbar. Sicherlich kann man wunderbar die Gewerke und ihre verschiedenen Tätigkeiten mit Hilfe einer App lernen. Man kann sogar virtuell ein ganzes Haus bauen mit allem was dazu gehört. Doch was hat man dann eigentlich getan? Auf dem Computer sind alle Handlungen gleich, egal ob man malt, schreibt, baut oder komponiert, immer werden nur Tasten gedrückt oder über eine Fläche gewischt. Das Gelernte ist also rein mental vorhanden, die körperliche und sinnliche Erfahrung fehlt jedoch fast vollständig.[^6] Diese Erfahrungen sind allerdings wesentlich, um etwas wirklich zu verinnerlichen, da das Gedächtnis auch an die Motorik gebunden ist. Nicht ohne Grund wird so viel im digitalen Bereich Gelerntes vergessen.[^7]

[^6]: Vgl. @hübner2015 S. 186 ff.

[^7]: Vgl. @ursprüng1990 S. 91

## Die Medien und das Spiel

Denn \[\...\] der Mensch spielt nur, wo er in voller Bedeutung des Wortes Mensch ist, und er ist nur da ganz Mensch, wo er spielt.[^8]

[^8]: @schiller2000 S. 62 f.

Diese Aussage von Friedrich Schiller weist schon auf eine tiefe Bedeutung des Spiels hin. Wenn Kinder die Möglichkeit haben, wirklich „frei" zu spielen, am besten in der Natur und nicht auf künstlichen Spielplätzen, dann haben sie, neben dem Spaß natürlich, die Chance die fundamentalen Kompetenzen des Lebens auszubilden. Sie lernen mit sich, den anderen und der Welt klarzukommen, sich zu organisieren und ernsthaft tätig zu sein. Die offene Natur ist der ideale Ort dafür, denn hier erfahren sie Freiheit, die Unmittelbarkeit und auch die Widerständigkeit der Umgebung und des Wetters und selbstverständlich müssen sie sich mit ihren Spielkameraden und manchmal auch mit den Erwachsenen auseinandersetzen. Auch traditionelle Spiele wie Fangen, Verstecken oder Blindekuh sind in dem Sinne wirkliche Kinderspiele, als sie von Kindern entwickelt, verändert und weitergeben werden. Hier gibt es auch immer sinnliche Erfahrungen, es geht um Mut oder Geschicklichkeit und selbstverständlich muss man sich mit seinen Mitspielern arrangieren. Digitale Spiele hingegen werden von Erwachsenen geschaffen und sie müssen kommerziell erfolgreich sein. Der Spaß will also genau dosiert und es darf auch weder zu leicht noch zu schwer sein. Und wenn es doch nicht klappt oder zu einfach ist, stellt man eben den Schwierigkeitsgrad um. Wenn es im Wald auf einmal anfängt zu regnen, dann muss man sich in irgendeiner Form damit arrangieren, der ist nicht einfach abstellbar. Auch den eventuellen Streit mit den Mitspielern kann man nicht einfach wegklicken.[^9]

[^9]: Vgl. @renz-polster2013 S. 159 ff.

Nun ist es sicherlich verlockend, das Spiel gezielt dazu zu nutzen, den Kindern bestimmte Bildungsinhalte zu vermitteln. Damit kann man schon sehr früh beginnen, da Kinder ja von klein auf gerne spielen und dann geht der Rest quasi wie von selbst, denn der Spiel- und Entdeckungstrieb hält die Kinder bei der Sache. Wenn es an digitalen Geräten passiert, kann man die Lernergebnisse danach ganz leicht vergleichen und Bestenlisten aufstellen. Der Wettkampf wird als ein zusätzlicher Anreiz genutzt, denn Kinder wie Erwachsene messen sich gerne. Nun ist Wettbewerb an sich nichts schlechtes, Kinder lernen viel und wachsen daran, allerdings ist auch hier, wie so oft, das rechte Maß entscheidend. Das Spiel wird dabei vollständig instrumentalisiert, es ist eine konkrete Richtung (Lernziel) vorgegeben und ein freies Ausprobieren ist schon technisch gar nicht möglich, da das Spiel natürlich nur das hergibt, was auch programmiert wurde. Wenn Kinder nun nur noch die Erfahrung machen, dass eigentlich immer nur die Leistung zählt, der Nachbar ein Rivale ist und nicht ein Freund, der mich auch unterstützen kann, dann geht das Denken und Empfinden der Kinder immer mehr in Richtung eines Konkurrenzdenken gegenüber dem Anderen. Das einfache, freie und unbekümmerte Spiel geht dann verloren. Dieses ist aber auch in Lernzusammenhängen wichtig, denn wenn Kinder und Jugendliche sich Sachverhalte und Zusammenhänge durch eigenes Suchen und Entdecken, spielerisches Ausprobieren und Gestalten erschließen, dann kann sich Wissen nachhaltig bilden und festigen.[^10] Den Nachweis, dass Lernprogramme tatsächlich einen Lerneffekt haben, bleiben die Hersteller schuldig. Bis dieser erbracht ist, muss davon ausgegangen werden, dass diese Programme reine Konditionierung anstatt wirklicher Lernerfolge bewirken.[^11]

[^10]: Vgl. @hüther2016 S. 107 f. und 187

[^11]: Vgl. @spitzer2012 S. 83 ff.
