---
toc: true
---

## Quellen der Gesundheit: Was Kinder stark (für Medien) macht

Wie schon im Abschnitt über die Entwicklung von Kindern und Jugendlichen: Menschenkundliche Aspekte dargestellt, ist die Ausbildung der Sinne elementar für die kindliche Entwicklung. Nun leben wir mit unseren Sinnen in einem verhältnismäßig kleinen Umfeld. Der Bereich von Schmecken, Riechen, Hören und Sehen ist beispielsweise von wenigen Zentimetern bis auf einige hundert Meter begrenzt. Mit unseren Gedanken und Empfindungen können wir dagegen fast überall sein. Die technischen Medien wie Telefon, Radio und Fernsehen und natürlich das Internet sind heute dafür unsere verlängerten Augen und Ohren, mit denen wir das begrenzte Umfeld unserer Sinne immens erweitern können. In dieser gegensätzlichen Welt müssen wir lernen, uns dem unmittelbaren Hier und Jetzt zugehörig zu fühlen, wir müssen lernen „bei uns" zu sein. Doch gerade Kinder müssen sich diesen unmittelbaren Lebensumkreis überhaupt erstmal erschließen. Möglichst natürliche sinnliche Erfahrungen mit kindgerechten Reizen, die nicht überfordern, sind die Basis dafür, denn über das sinnliche Bewusstsein kommen wir zu einem Bewusstsein unserer selbst.[^1]

[^1]: Vgl. @renz-polster2013 S. 43 f.

Der Umstand, dass heute per Knopfdruck ein ungeheures Wissen abgefragt werden kann, ersetzt jedoch die menschliche Bildung nicht. Kreativität kann keine Maschine vermitteln. Die braucht es aber, um neue Ideen in die Welt zu setzen. Die Frage ist also: Wie entwickelt sich Persönlichkeit? Die Grundlagen dafür wachsen von innen in einem Menschen heran und dafür braucht es eine Entwicklungsraum, in dem sich Kinder erproben und auch Grenzerfahrungen machen können.[^2] Wenn sich Kinder wirklich mit ihrem Tun verbinden können, wenn sie stundenlang im Spiel versinken oder sonst einer Beschäftigung nachgehen und alles um sich herum vergessen, so ist dies ein Zustand höchster Präsenz und innerer Verbundenheit. Die Erfahrungen des Entdeckens und der eigenen Gestaltung kann dabei mehr beglücken als das Lob für eine besondere Leistung am Ende. Diese sogenannten Kohärenzzustände („Flow-Erlebnisse") und die damit verbundene Freisetzung neuroplastischer Botenstoffe sind aus neurobiologischer Sicht wahrer Dünger für die kindliche Gehirnentwicklung. Wichtig ist, dass die Kinder ihr Tun als selbstbestimmt erleben, was heutzutage durch die vielfältigen, sich von außen aufdrängenden Eindrücken, häufig korrumpiert wird.[^3]

[^2]: Vgl. @renz-polster2013 S. 68 f.

[^3]: Vgl. @renz-polster2013 S. 71 ff.

Eine ähnliche Wirkung auf Kinder haben Geschichten und auch Erwachsene können diese Erfahrung machen. Alle Erzählungen sind im Grunde auch Medien, ob nun mündlich weitergegeben, in Buchform oder als Film und sie sind in der Regel dann am spannendsten, wenn sie von den Dingen handeln, die uns auch im realen Leben am meisten motivieren können: Wirksames Handeln, Überwindung von Widerständen, Zugehörigkeit und Geborgenheit. Sie sind Vermittler zwischen unserer Innenwelt, den Gefühlen und Gedanken und einer nicht selbst erlebten, virtuellen, Welt.[^4] Die Qualität der Inhalte ist sicherlich ein entscheidendes Merkmal, doch die ist weniger von der Medienform abhängig (die Summe an minderwertigen Printerzeugnissen, Radio- oder Fernsehbeiträgen dürfte in etwa gleich hoch sein). Die Unterhaltungsindustrie setzt allerdings vermehrt auf übermächtige Figuren und Helden, die die Kinder in ihren Bann ziehen, weil sie Macht ausstrahlen. Sie haben oft sehr einseitige Qualitäten, sind schön, schlau und stark, mit teilweise übermenschlichen Fähigkeiten und selbstverständlich gewinnen sie auch immer. Eine Entwicklung der Protagonisten, wie es in Märchen und anderen Geschichten passiert, findet in der Regel nicht statt. In den Fernsehserien, die ja immer weitergehen müssen, kommt es aber selten zu einer wirklichen Lösung und so bleibt auch das Böse immer im Hintergrund in Wartestellung und das Kind in einer zweifelhaften, gefährlichen Welt.[^5]

[^4]: Vgl. @renz-polster2013 S. 115

[^5]: Vgl. @renz-polster2013 S. 147 f.

## Salutogenese und Pädagogik

Kinder entwickeln sich naturgemäß gegen zahlreiche Widerstände und sie müssen lernen mit ihnen umzugehen bzw. sie zu überwinden. Was dazu an psychischen Kräften vonnöten ist, wird heute in der Resilienzforschung untersucht und auch warum dies einigen Kindern scheinbar besser oder leichter gelingt als anderen. Das oben schon erwähnte Kohärenzgefühl ist ausschlaggebend dafür, denn es ist ein Gefühl, welches den Menschen in schwierigen Situationen innerlich zusammenhält und ihm die Sicherheit gibt, auch in der äußeren Umgebung Halt und Hilfe zu finden. Es ist ein Gefühl der Grundsicherheit im Leben. Das Konzept der Salutogenese (von lat. salus: Unverletztheit, Heil, Glück; griech. genesis: Werden, Entstehen) sieht die Gesundheit des Menschen als einen fortwährenden Prozess an und nicht als einen Zustand der immer dann gegeben ist, wenn man nicht krank ist. In diesem Konzept werden drei Komponenten beschrieben, die dem Kohärenzgefühl zugrunde liegen und die zusammenkommen müssen, damit es eintreten und gesundend wirken kann.

·       **Verstehbarkeit** ist das Erleben der eigenen Welt als stimmig und geordnet. Dies geht einher mit der Möglichkeit, persönliche Erlebnisse, aber auch Probleme und Belastungen in einen größeren Zusammenhang gedanklich einordnen zu können.

·       Die zweite Komponente ist die Empfindung der **Sinnhaftigkeit** des eigenen Tuns in Bezug auf die vom Leben gestellten Aufgaben und Herausforderungen, das Engagement für bestimmte Projekte und Ziele sowie das Gefühl von Bedeutsamkeit.

·       Das Gefühl der **Handhabbarkeit** ist die dritte Komponente. Hier geht es um das Gefühl, dass die Aufgaben, die das Leben stellt, lösbar sind, das Vertrauen in die eigenen Fähigkeiten und innere und äußere Ressourcen. Auch der Glaube an Hilfen, sei es durch andere Menschen oder höhere Mächte, gehört dazu, denn sicherlich ist nicht alles aus eigener Kraft zu bewältigen.

Der mit dem Kohärenz*gefühl* einhergehende Kohärenz*sinn*, beschreibt die aus dem Gefühl folgende, gedanklich aktive Weltsicht.[^6]

[^6]: Vgl. @schiffer2001 S. 28 f.

![Modell der Salutogenese[^7]](images/salutogenese.jpg){#fig-salutogenese}

[^7]: @schiffer2001 S. 29

[^8]: @schiffer2001 S. 29

Die Eigenschaften und Wirkungen der Medien behindern diese salutogenetischen Faktoren. Die Zusammenhanglosigkeit der einzelnen Beiträge löst die Verstehbarkeit auf, sie müssen aus eigener Kraft in den jeweiligen Kontext gestellt werde. Die Teilhabe an den Medieninhalten, ohne das Gefühl zu haben etwas ändern oder bewirken zu können, was beispielsweise durch Reportagen oder Nachrichten ausgelöst werden kann, wirkt sich auf das Gefühl der Handhabbarkeit aus. Wenn eine Situation jedoch weder verstehbar noch handhabbar ist, wird sie sinnlos und führt im schlimmsten Fall zur Überforderung.[^9]

[^9]: Vgl. @hübner2015 S. 283

Das im Abschnitt „Die Medien und das Spiel" erwähnte freie Spiel kann eine stabile Basis im Sinne der Salutogenese sein. Hier lernen Kinder neben Selbstwirksamkeit, Selbstorganisation auch soziale Aspekte. Das Spiel ist in hohem Maße beziehungsfördernd und die Beziehungen sind lebensnotwendig. Diese Kompetenzen sind allerdings durch keine Pädagogik vermittelbar. Kinder müssen ihre Kreativität und ihre innere Stärke im alltäglichen Miteinander, mit anderen Menschen, mit jüngeren und älteren Kindern, erfahren um sie entwickeln zu können.[^10]

[^10]: Vgl. @renz-polster2013 S. 23
